import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const products=[["⚽","Pro Football","Football",1299,"Bestseller"],["👟","Elite Running Shoes","Footwear",3499,"New"],["🎾","Carbon Tennis Racket","Tennis",4299,"Pro Pick"],["🏏","Performance Cricket Bat","Cricket",2899,"Popular"],["🏀","Training Basketball","Basketball",1199,"Popular"],["🥊","Gym Training Gloves","Fitness",699,"Value"],["🎒","Sports Backpack","Accessories",1499,"New"],["🥤","Fitness Water Bottle","Accessories",499,"Value"]].map((p,i)=>({id:i+1,icon:p[0],name:p[1],cat:p[2],price:p[3],tag:p[4],rating:(4.5+i%5/10).toFixed(1)}));
function App(){const[q,setQ]=useState(""),[cat,setCat]=useState("All"),[cart,setCart]=useState([]),[menu,setMenu]=useState(false);const cats=["All","Football","Footwear","Tennis","Cricket","Basketball","Fitness","Accessories"];const list=useMemo(()=>products.filter(p=>(cat==="All"||p.cat===cat)&&p.name.toLowerCase().includes(q.toLowerCase())),[q,cat]);const add=p=>setCart(c=>{let x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});const change=(id,n)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:i.qty+n}:i).filter(i=>i.qty>0));const count=cart.reduce((s,i)=>s+i.qty,0),total=cart.reduce((s,i)=>s+i.price*i.qty,0);return <><header><a className="logo" href="#home">⚡ SPORTIVA</a><nav className={menu?"open":""}>{["Home","Shop","Sports","About"].map(x=><a href={"#"+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}</nav><div className="actions"><div className="search">⌕<input placeholder="Search sports gear..." value={q} onChange={e=>setQ(e.target.value)}/></div><button onClick={()=>document.getElementById("cart").scrollIntoView({behavior:"smooth"})}>🛒 Cart <b>{count}</b></button><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button></div></header>
<section className="hero" id="home"><div><small>GEAR UP. PLAY HARD. WIN.</small><h1>Built for<br/><i>your game.</i></h1><p>Premium sports equipment and activewear for athletes who want to train harder, move faster and perform better.</p><a className="primary" href="#shop">Shop the collection →</a> <a className="secondary" href="#sports">Explore sports</a><div className="stats"><b>5K+<span>Athletes</span></b><b>4.9★<span>Average rating</span></b><b>48H<span>Fast dispatch</span></b></div></div><div className="hero-art"><div className="circle"></div><div className="ball">⚽</div><div className="shoe">👟</div><strong>PRO<br/>SERIES</strong></div></section>
<section className="sports" id="sports"><small>FIND YOUR SPORT</small><h2>Shop by sport</h2><div className="sport-grid">{[["⚽","Football"],["🏏","Cricket"],["🎾","Tennis"],["🏀","Basketball"],["🏃","Fitness"]].map(([i,n])=><button onClick={()=>{setCat(n);document.getElementById("shop").scrollIntoView({behavior:"smooth"})}}><span>{i}</span><b>{n}</b> →</button>)}</div></section>
<section className="shop" id="shop"><div className="head"><div><small>TOP PICKS</small><h2>Gear for every game</h2></div><div className="filters">{cats.map(c=><button className={cat===c?"active":""} onClick={()=>setCat(c)}>{c}</button>)}</div></div><div className="grid">{list.map(p=><article><div className="visual"><em>{p.tag}</em><span>{p.icon}</span></div><div className="info"><small>{p.cat}</small><h3>{p.name}</h3><label>★ {p.rating} · 120+ reviews</label><div><strong>₹{p.price.toLocaleString()}</strong><button onClick={()=>add(p)}>Add to cart</button></div></div></article>)}</div></section>
<section className="banner"><div><small>ATHLETE ESSENTIALS</small><h2>Train today.<br/>Perform tomorrow.</h2><p>Get the equipment you need to turn every training session into progress.</p><a href="#shop">Shop essentials →</a></div><span>🏆 🏃 ⚡</span></section>
<section className="cart" id="cart"><div className="head"><div><small>YOUR ORDER</small><h2>Shopping cart</h2></div><label>{count} items · ₹{total.toLocaleString()}</label></div>{!cart.length?<div className="empty">Your cart is empty. Add your game gear! 🛍️</div>:<div className="cartbox">{cart.map(i=><div className="row"><span>{i.icon} <b>{i.name}</b></span><span>₹{i.price}</span><span><button onClick={()=>change(i.id,-1)}>−</button> {i.qty} <button onClick={()=>change(i.id,1)}>+</button></span><b>₹{(i.price*i.qty).toLocaleString()}</b></div>)}<div className="checkout"><b>Total ₹{total.toLocaleString()}</b><button onClick={()=>alert("Demo checkout — connect your payment gateway here.")}>Checkout →</button></div></div>}</section>
<section className="about" id="about"><small>ABOUT SPORTIVA</small><h2>Play with purpose.</h2><p>Sportiva is a modern sports-shop frontend demo built with React, HTML, CSS and JavaScript. Replace the sample products and branding with your real store data.</p></section><footer>⚡ SPORTIVA <span>Gear up for your next challenge. · © 2026</span></footer></>}
createRoot(document.getElementById("root")).render(<App/>);